# Cloud Run Service Configuration
# Free Tier Optimized

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-interviewer-adk
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        # Free tier: min 0 instances (scale to zero)
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
        # Free tier: 256MB memory, 1 CPU
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/ai-interviewer-adk:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api-key
                  key: latest
            - name: LOG_LEVEL
              value: "INFO"
